### PR TITLE
2.4.1 rtl

### PR DESCRIPTION
**Pull request by felixmosh**
Build of RTL version of 2.4.1

### CODE REVIEW

**Comment by felixmosh** [comment]
@MohammadYounes can you review that? I've created a local branch from 2.4.1 release, cherry picked your commits, and `npm run install`, all passed.

**Comment by felixmosh** [comment]
@MohammadYounes, ping

**Comment by MohammadYounes** [comment]
PR still has problems and doesn't build the RTL version, I rebased and pushed the changes.

Version 2.4.1 will be published soon.

**Comment by felixmosh** [comment]
Thanx!

**Pull request closed without merging**
